on:
  push:
    branches:
      - master

jobs:
  build-win:
    runs-on: windows-latest
    if: "contains(github.event.head_commit.message, '[build]')"
    steps:
      - uses: actions/checkout@v4
      - id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install poetry
      - run: python -m poetry install --no-interaction
      - run: python -m poetry run pwsh .\build_exe.ps1
      - uses: actions/upload-artifact@v4
        with:
          name: win
          path: dist\main\
